spring:
  application:
    name: Mylib
  datasource:
    url:
    username:
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddlAuto: create
  devtools:
    restart:
      pollInterval: 2s
      quietPeriod: 1s
    remote:
      enable: false
    jmx:
      enabled: false